version: '3'

services:
   web:
     container_name: web
     image: worldofgeese/web:v0.1.0

   roach-0:
     image: cockroachdb/cockroach:v22.1.10
     container_name: roach-0
 
   roach-1:
     container_name: roach-1
     image: cockroachdb/cockroach:v22.1.10
     depends_on: 
       - roach-0
 
   roach-2:
     container_name: roach-2
     image: cockroachdb/cockroach:v22.1.10
     depends_on:
       - roach-0