# pull official base image
FROM python:3.11-alpine

EXPOSE 5000

# set work directory
WORKDIR /usr/src/app

# copy project
COPY --chmod=755 web/. /usr/src/app/

# # install system dependencies
# RUN apt-get update && apt-get install -y \
#     netcat \
#     # build tools needed for psycopg2 required by sqlalchemy-cochroachdb
#     libpq-dev \
#   && rm -rf /var/lib/apt/lists/* \
#   && pip install --no-cache-dir --upgrade pip \
#   && pip install --no-cache-dir -r requirements.txt

RUN apk add --no-cache netcat-openbsd \
    # build tools needed for psycopg2 required by sqlalchemy-cochroachdb
    postgresql-libs \
    && apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev \
    # build tool needed to build greenlet
    g++ \
    && pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && apk --purge del .build-deps

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /usr/src/app
USER appuser

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
